--Terminal setup.
vim.cmd("tnoremap <A-h> <C-\\><C-N><C-w>h")
vim.cmd("tnoremap <A-j> <C-\\><C-N><C-w>j")
vim.cmd("tnoremap <A-k> <C-\\><C-N><C-w>k")
vim.cmd("tnoremap <A-l> <C-\\><C-N><C-w>l")
vim.cmd("inoremap <A-h> <C-\\><C-N><C-w>h")
vim.cmd("inoremap <A-j> <C-\\><C-N><C-w>j")
vim.cmd("inoremap <A-k> <C-\\><C-N><C-w>k")
vim.cmd("inoremap <A-l> <C-\\><C-N><C-w>l")
vim.cmd("nnoremap <A-h> <C-w>h")
vim.cmd("nnoremap <A-j> <C-w>j")
vim.cmd("nnoremap <A-k> <C-w>k")
vim.cmd("nnoremap <A-l> <C-w>l")

--Tab switching bindings.
vim.cmd("nnoremap <A-1> 1gt")
vim.cmd("nnoremap <A-2> 2gt")
vim.cmd("nnoremap <A-3> 3gt")
vim.cmd("nnoremap <A-4> 4gt")
vim.cmd("nnoremap <A-5> 5gt")
vim.cmd("nnoremap <A-6> 6gt")
vim.cmd("nnoremap <A-7> 7gt")
vim.cmd("nnoremap <A-8> 8gt")
vim.cmd("nnoremap <A-9> 9gt")
vim.cmd("nnoremap <A-0> 10gt")
vim.cmd("nnoremap H gT")
vim.cmd("nnoremap L gt")
